### ISSUE TITLE
Closing scripts in the "running scripts" windows does not stop the script only removes it from the list

### ISSUE THREAD

**Issue by Basinsky** [overte-org/overte#506] opened 2023-07-03 19:08 UTC
If you have an interface script running and close it from running scripts, it is removed from the list but keeps running in the backgrouind.  If you assign keypresses you can see that the script is still working.

**Comment by daleglass** [comment] 2023-07-08 19:44
Dev meeting: may have been a prior issue

**Comment by AleziaKurdis** [comment] 2023-07-10 01:46
Suspected to be parent with tjhis issue: 
If we do "Edit > Reload Content (Clears all caches)"
in HMD we get multiple instance of the "Menu" app.
I got many script starting to badly works (probably conflicting with them self.)
This makes very difficult to develop complex script ensemble.
We have to restart interface to get correct results.

Top me this is currently the **top priority bug to address**. It rotten my efforts if I can only trust a restart of interface to be able to trust the results and not waste a tone of time to figure false results.

**Comment by JulianGro** [comment] 2023-07-10 20:40
> Dev meeting: may have been a prior issue

I just checked, and it is indeed a regression. It doesn't seem to happen on the 2022.12.1 release.

**Comment by ksuprynowicz** [comment] 2023-07-18 18:37
It looks like the signals are not unregistered when script engine is destroyed.
When I try this script, timer stops, but click event still happens:
```
Script.setInterval(function () {
    print("Reload test: Interval timer fired");
}, 1000);

Entities.clickDownOnEntity.connect(function (entityID, event) {
    print("Reload test: Clicked on entity ; " + event.type);
});
```

**Comment by ksuprynowicz** [comment] 2023-07-18 20:18
Script manager and script engine destructor never gets called. It looks like smart pointer issue.

**Comment by ksuprynowicz** [comment] 2023-07-18 21:38
Smart pointer is succesfully getting removed from maps in ScriptEngines:
```
QMultiHash<QUrl, ScriptManagerPointer> _scriptManagersHash;
QSet<ScriptManagerPointer> _allKnownScriptManagers;
```
But it looks like there are still 4 usages after this. One is in the local scope, but I have no idea how to track down 3 remaining ones.

**Comment by ksuprynowicz** [comment] 2023-07-19 22:19
Fixed by https://github.com/overte-org/overte/pull/521

**Closed** 2023-07-22 12:03 UTC
Labels: bug, v8, fix before release
