### ISSUE TITLE
Add exposure setting to graphics menu

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#91] opened 2022-06-18 20:15 UTC
well, everyone's setup is different and the environment being too dark seems to be an issue for some.

There is already an (undocumented) "exposure" setting available in the render API so it is already doable via scripting.

For anyone wanting it NOW 😄 it is part of my menu extender that I always run:
https://silverfish-freestuff.s3.amazonaws.com/Scripts/MenuExtender/MenuExtender3.js
It is in the "Xtra-Graphics->Tone Mapping" menu
![Screenshot 2022-06-18 22 13 52](https://user-images.githubusercontent.com/53531160/174455783-fad4ac69-f171-4995-be4c-97731751c88a.png)

**Comment by HifiExperiments** [comment] 2024-06-28 22:37
dupe of #740 (that one’s newer but mentions additional flags)

**Closed by HifiExperiments** 2024-06-28 22:37 UTC
Labels: enhancement, good first issue
