### ISSUE TITLE
 Low angular velocity is rounded to 0

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#1170] opened 2024-10-19 20:02 UTC
In the create app, if You set set the angular velocity in create app lower than about 0,459 it stops and angular velocity is rounded to 0.

I believe it is deg/s here and  0.459 is really not that slow, especially for something like a skybox.
Once it has stopped, Sometimes you actually have to set it very high, like 2 or so, to make in spin again.

The issue is also present if You set the angular velocity by script, but here the minimum values about 0.008 since the values there are in rad/s.

```
Entities.editEntity(UUID", {
angularVelocity: { x: 0, y: 0.007, z: 0 }
})
```
`JSON.stringify(Entities.getEntityProperties("118ec170-205f-44c3-b9f8-7d6a34f5b441", ["angularVelocity"]))`

**Comment by ksuprynowicz** [comment] 2024-10-19 20:37
I think that to fix it we need to change this value:
https://github.com/overte-org/overte/blob/60b8d41c164e236b87d3c22bac1d685c2d25fcfd/libraries/entities/src/EntityItem.cpp#L2005
```C++
void EntityItem::setAngularVelocity(const glm::vec3& value) {
    glm::vec3 angularVelocity = getLocalAngularVelocity();
    if (angularVelocity != value) {
        float speed = glm::length(value);
        if (!glm::isnan(speed)) {
            const float MIN_ANGULAR_SPEED = 0.0002f;
            const float MAX_ANGULAR_SPEED = 9.0f * TWO_PI; // 1/10 rotation per step at 90Hz
            if (speed < MIN_ANGULAR_SPEED) {
                angularVelocity = ENTITY_ITEM_ZERO_VEC3;
```

**Comment by AleziaKurdis** [comment] 2024-10-19 20:40
We already had a bug about that, it didn't get address.
0.0002 might be a barrier here

**Comment by ksuprynowicz** [comment] 2024-10-19 20:46
> We already had a bug about that, it didn't get address. 0.0002 might be a barrier here

You are right. That was the hardcoded limit. I changed it to 20 times lower, so we should test and see once PR build is ready.

**Comment by ksuprynowicz** [comment] 2024-10-20 21:38
If I comment out the part that reads angular velocity from network packet, it's stops in exactly same way, so the problem is local.

**Comment by ksuprynowicz** [comment] 2024-10-21 14:09
https://github.com/overte-org/overte/pull/1171

**Comment by ksuprynowicz** [comment] 2024-10-21 14:10
Fixed by https://github.com/overte-org/overte/pull/1171

**Closed** 2024-10-22 12:03 UTC
