### ISSUE TITLE
Mic test in audio settings stays active even if audio settings gets closed while active

### ISSUE THREAD

**Issue by rampa3** [overte-org/overte#1140] opened 2024-09-13 13:58 UTC
The microphone test in Overte's audio settings stays active when the audio settings get closed with it being still active, which results in user hearing themselves. This can lead to a confusion, if the user does not realise that the mic test stayed active.

In my opinion, the mic test should automatically end when audio settings are closed.

**Comment by Armored-Dragon** [comment] 2024-09-13 20:30
Duplicate of #316.
This will be resolved soon:tm:!

**Closed by Armored-Dragon** 2024-09-13 20:30 UTC
