### ISSUE TITLE
cannot receive websocket messges

### ISSUE THREAD

**Issue by SilverfishVR** [overte-org/overte#1016] opened 2024-06-10 23:50 UTC
The `webSocket.onmessage` event never fires so you never get a response from a websocket server.

Tested to be broken on:
* 2024.06.01
* 2024.05.-rc2
* PR937-62bfab9

Tested to be working on:
* 2023.11.1

Test procedure:
* open entity script server log and console.
* Put this on an entity as server script.
https://silverfish-freestuff.s3.amazonaws.com/TestStuff/testWS.js

You should get 2 responses on reload,  _Request served by 7811941c69e658_ and _Hello World_. To send custom message, put this in the console:` Entities.callEntityServerMethod("[ENTITY ID]", "sendMSG", ["message"]);`
You should get an echo back.

**Comment by ksuprynowicz** [comment] 2024-06-11 06:03
Thanks for noticing this!
Since it's a serious issue, we should probably fix it before announcing the release. I will look into it today.

**Comment by ksuprynowicz** [comment] 2024-06-11 19:37
I just tested it with script running client-side, and it works correctly there.
One thing I noticed is that wen script ran and then there was no communication for a logn time, it seemed to time out and not reply anymore.
I need to test server side next.

**Comment by ksuprynowicz** [comment] 2024-06-11 19:55
I just tested it server-side, and I'm getting the message too:
```
[
    {
        "entityID": "{c38b48fe-2973-4957-bc8c-ec327f4417df}",
        "fileName": "about:Entities 1",
        "lineNumber": 23,
        "message": "Sending WS message:  glob",
        "severity": 1,
        "type": 1
    }
]
```

**Comment by ksuprynowicz** [comment] 2024-06-11 19:56
Is both your server and client running 2024.06.01?

**Comment by ksuprynowicz** [comment] 2024-06-11 20:21
On another server I seem to be running into a similar issue as described. It seems that the websocket is immediately closed after script starts:
```JS
[
    {
        "entityID": "{51f039ae-c54d-4e51-bfbe-989a7ad6fb41}",
        "fileName": "about:Entities 2",
        "lineNumber": 32,
        "message": "Closing WebSocket",
        "severity": 1,
        "type": 1
    }
]
[
    {
        "entityID": "{51f039ae-c54d-4e51-bfbe-989a7ad6fb41}",
        "fileName": "about:Entities 2",
        "lineNumber": 14,
        "message": "Sending dummy WS message:  ah",
        "severity": 1,
        "type": 1
    }
]
[
    {
        "entityID": "{51f039ae-c54d-4e51-bfbe-989a7ad6fb41}",
        "fileName": "about:Entities 2",
        "lineNumber": 17,
        "message": "Sending WS message:  Hello World",
        "severity": 1,
        "type": 1
    }
]
```

**Comment by ksuprynowicz** [comment] 2024-06-11 20:25
I was wrong, I think "Closing WebSocket" is from previous script being shut down when reloading.
I think the issue is that for some reason sendMSG doesn't seem to be called at all.

**Comment by ksuprynowicz** [comment] 2024-06-11 20:27
It turns out I was using wrong entity ID on second server. Everything seems to work correctly now.

**Comment by SilverfishVR** [comment] 2024-06-11 20:29
> I just tested it server-side, and I'm getting the message too:
> 
> ```
> [
>     {
>         "entityID": "{c38b48fe-2973-4957-bc8c-ec327f4417df}",
>         "fileName": "about:Entities 1",
>         "lineNumber": 23,
>         "message": "Sending WS message:  glob",
>         "severity": 1,
>         "type": 1
>     }
> ]
> ```

yes, that is sending the message, but there is no reply _"WS Message received: glob"_  right?

**Comment by SilverfishVR** [comment] 2024-06-11 20:35
_"Closing WebSocket"_ is indeed from unloading/reloading the script.

* "Is both your server and client running 2024.06.01?" Yes, all tests are with matching server/client versions.

**Comment by ksuprynowicz** [comment] 2024-06-11 20:37
Can you share script log when you reload script and almost immediately trigger sendMSG?

**Comment by SilverfishVR** [comment] 2024-06-11 20:49
this is what I get on 2023.11.1:

```
[06/11 22:39:56] [DEBUG] [overte.scriptengine.script] [9972] [entity-script-server] [about:Entities 1] Sending dummy WS message:  ah
[06/11 22:39:56] [DEBUG] [overte.scriptengine.script] [9972] [entity-script-server] [about:Entities 1] WS Message received:  Request served by 7811941c69e658
[06/11 22:39:56] [DEBUG] [overte.scriptengine.script] [9972] [entity-script-server] [about:Entities 1] Sending WS message:  Hello World

[06/11 22:39:56] [DEBUG] [overte.scriptengine.script] [9972] [entity-script-server] [about:Entities 1] WS Message received:  Hello World
[06/11 22:40:08] [DEBUG] [overte.scriptengine.script] [9972] [entity-script-server] [about:Entities 1] Sending WS message:  test message

[06/11 22:40:08] [DEBUG] [overte.scriptengine.script] [9972] [entity-script-server] [about:Entities 1] WS Message received:  test message
```

On 2024.06.1 I get the same as you did, 
_"Closing WebSocket"_
_"Sending dummy WS message:  ah"_
_"Sending WS message:  Hello World"_

but nothing from the `webSocket.onMessage` callback function.

I do wonder if it could be related to the extra debugging that is happening now #992 because the ones that have it also never receive WS messages, could be coincidental though.

**Comment by ksuprynowicz** [comment] 2024-06-11 20:52
So "Sending WS message: " is not printed either?

**Comment by SilverfishVR** [comment] 2024-06-11 20:56
no
2024.06.1 reloading and sending message:

```
====================== Subscribed to the Entity Script Server's log ======================
[
    {
        "entityID": "{712a160d-3379-4eeb-8df5-3a06df90e65b}",
        "fileName": "about:Entities 1",
        "lineNumber": 32,
        "message": "Closing WebSocket",
        "severity": 1,
        "type": 1
    }
]
[
    {
        "entityID": "{712a160d-3379-4eeb-8df5-3a06df90e65b}",
        "fileName": "about:Entities 1",
        "lineNumber": 14,
        "message": "Sending dummy WS message:  ah",
        "severity": 1,
        "type": 1
    }
]
[
    {
        "entityID": "{712a160d-3379-4eeb-8df5-3a06df90e65b}",
        "fileName": "about:Entities 1",
        "lineNumber": 17,
        "message": "Sending WS message:  Hello World",
        "severity": 1,
        "type": 1
    }
]
[
    {
        "entityID": "{712a160d-3379-4eeb-8df5-3a06df90e65b}",
        "fileName": "about:Entities 1",
        "lineNumber": 23,
        "message": "Sending WS message:  test message",
        "severity": 1,
        "type": 1
    }
]
```

**Comment by ksuprynowicz** [comment] 2024-06-11 20:56
Is the server running on Windows or Linux?

**Comment by ksuprynowicz** [comment] 2024-06-11 23:46
I got workaround for it, but it will currently impossible to figure out entity ID for this message:
```JS
[
    {
        "entityID": "{f9668220-9f6d-4457-9df0-ac46bb537b79}",
        "fileName": "about:Entities 1",
        "lineNumber": 23,
        "message": "Sending WS message:  glob",
        "severity": 1,
        "type": 1
    }
]
[
    {
        "entityID": "{00000000-0000-0000-0000-000000000000}",
        "fileName": "about:Entities 1",
        "lineNumber": 28,
        "message": "WS Message received:  glob",
        "severity": 1,
        "type": 1
    }
]
```

**Comment by ksuprynowicz** [comment] 2024-06-11 23:49
Getting proper entity ID would probably mean massive rework of script engine sadly

**Closed** 2024-06-15 19:23 UTC
