### ISSUE TITLE
Keyboard sometimes becomes permanently attached to hand when grabbed in VR mode

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#531] opened 2023-07-29 15:32 UTC

**Comment by AleziaKurdis** [comment] 2023-08-22 01:52
Duplicate of https://github.com/overte-org/overte/issues/565
this is a ungrab that doesn't work for local entities.

We can close this one and keep the 565 open.

**Comment by AleziaKurdis** [comment] 2023-08-22 01:54
Closing it as duplicate of 565.

**Closed by AleziaKurdis** 2023-08-22 01:54 UTC
