### ISSUE TITLE
(Feature request) Add a way to assign keys to controls

### ISSUE THREAD

**Issue by hardBSDk** [overte-org/overte#1198] opened 2024-10-27 12:43 UTC

**Comment by Armored-Dragon** [comment] 2024-10-27 16:29
This has been a longstanding issue for a while. There have been attempts in the past to bring this functionality into this software but they never got completed.
See: https://github.com/overte-org/overte/milestone/4
I will likely be implementing this (or try to at least) with the UUI update https://github.com/orgs/overte-org/projects/8
Closing as (technically) a duplicate of https://github.com/overte-org/overte/issues/110

**Closed by Armored-Dragon** 2024-10-27 16:29 UTC
