### ISSUE TITLE
Web portal not updating port

### ISSUE THREAD

**Issue by OfficialR3ido101** [overte-org/overte#517] opened 2023-07-14 14:58 UTC
The User UI Does not update port on submit of form.

![image](https://github.com/overte-org/overte/assets/39566484/3fe93765-51e4-4d00-a586-276c5dab29a6)

**Comment by JulianGro** [comment] 2023-08-04 11:15
Duplicate of https://github.com/overte-org/overte/issues/318

**Closed by JulianGro** 2023-08-04 11:15 UTC
Labels: bug, server
