### ISSUE TITLE
Add a safety option to block opening sites from Web entities and Interface scripts until user allows/whitelists them

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#9] opened 2022-02-05 20:45 UTC
Web entities open automatically, and could be used to open malicious content. There should be an option to allow users to block those by default and whitelist them. Untrusted scripts could also be a security concern.
Let me know what are your opinions on this.

**Comment by Kreolis484** [comment] 2022-12-10 18:36
#250 is the same

**Comment by Armored-Dragon** [comment] 2024-06-06 20:52
Closing as duplicate of #250. While this issue is older, the other one has more discussion.

**Closed by Armored-Dragon** 2024-06-06 20:52 UTC
Labels: enhancement
