### ISSUE TITLE
Snap app shows tablet when making a snap on desktop 

### ISSUE THREAD

**Issue by Basinsky** [overte-org/overte#608] opened 2023-08-28 21:19 UTC
When using the snap app and snapping a picture. The tablet is in the picture (and on the gif)
![overte-snap-by-Basinsky-on-2023-08-28_23-22-01](https://github.com/overte-org/overte/assets/51274563/8e45c195-353f-4701-89fa-eaabd3b16f2b)
this is on 2023.07.1-RC3

**Comment by JulianGro** [comment] 2023-09-02 19:31
Duplicate of https://github.com/overte-org/overte/issues/504

**Closed by JulianGro** 2023-09-02 19:31 UTC
